[package]
name = "samourai-wallet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bip47 = "0.4"
bdk = "0.3"
